### ISSUE TITLE
interface incoherencies

### ISSUE THREAD

**Issue by Offirmo** [ckknight/random-js#20]
I'm trying random-js.

The interfaces are strange. It would make sense to have parameters 1st, engine separated, like in `Random.integer`, `Random.real`, `Random.bool`

Pick:
- actual `Random.pick(engine, array[, begin[, end]])`
- expected: shouldn't it be `Random.pick(array[, begin[, end]])(engine)` ?

Generating an uuid4:
- actual `Random.uuid4(engine)`
- expected: shouldn't it be `Random.uuid4()(engine)` ?

And so on. Is it due to implementation constraints ? Or were you mirroring the C++ lib ?

**Comment by Pencroff** [comment]
Probably you have missed [Alternate api](https://github.com/ckknight/random-js#alternate-api)

**Comment by Offirmo** [comment]
Hi @Pencroff I didn't. It's just a matter of consistency between call signatures of the 1st API.

I was wonderinq if there was a reason.

**Comment by ckknight** [comment]
In the cases where `engine` is part of the overarching argument list, it is because that was more efficient for that case.

In your `pick` example, you're describing `picker`, which does take the `array`, `begin`, and `end`, and can do some pre-calculation in order to be more efficient. It is typical to pick one value from an array and not hold onto that array's reference, so both functions are available.

For the `uuid4` example, what would `uuid4()` do except return the current implementation?

I do see what you're saying about the inconsistency of it, though there is a method to the madness of it.

**Comment by Offirmo** [comment]
By the way your lib is a critical part of all my personal projects for 2 years now. Reliable, never let me down.

My main use is in my pet game: https://www.online-adventur.es/apps/the-boring-rpg/

Glad to see it's still active!

I forked it in the meantime, but most changes are no longer relevant since last versions of TypeScript https://github.com/Offirmo/random-js/commits/master

Since you are working on a v2, my main problem is being able to store the state of a Mersenne Twister generator and restore it later. I had to read the source and mess with the undocumented property `_seed`. Or maybe I missed something?
