### ISSUE TITLE
Is it good to feed MersenneTwister19937 with array of same integers except one?

### ISSUE THREAD

**Issue by imShara** [ckknight/random-js#31]
What's better for uniform random with MersenneTwister19937 seed? Here is pseudocode:

1. One 32bit value with 
```js
const bit32 = 2147483647
const seed = random.integer(0, bit32)
MersenneTwister19937.seed(value)
```

2. Or > 32bit value with array
```js
const bit32 = 2147483647
const largeNumber = 56800235583
const rnd = random.integer(0, largeNumber)
const div = Math.floor(rnd / bit32)
const mod = rnd - (bit32 * div)
let seed = Array(div).fill(bit32)
seed.push(mod)
MersenneTwister19937.seedWithArray(seed)
```

Can't see any difference, but is it mathematically-correct?

![548260550-ttmwuzkiqecfirjkhyeftlcjwdctfgos](https://user-images.githubusercontent.com/4913196/53683006-d1300d80-3d0c-11e9-9eb1-baec850dc802.png)

**Comment by ckknight** [comment]
Short answer: no.

Long answer:
Both will be uniformly random, given the nature of how the Mersenne Twister works. Seeding with `[a]` compared to `[a, a]` will give a different view of entropy, as would `[a, a + 1]`. I don't particularly recommend using an array all of the same value, as it's not inherently more uniform than using a single-value seed.

Seeding with an array is available so that if you have multiple sources of data that you wish to base the twister on, it's straightforward and easy, while also providing a source seed that has more than `2**32` combinations. Using the same value repeatedly still leaves one with `2**32` combinations rather than `2**64` or `2**96`.

**Comment by imShara** [comment]
Thanks, I understand you, but asked not good.

My problem was actually with increasing seed value to increase number of random sequences. `largeNumber` should  be > 32bit value and converted to array of 32bit values.
