### ISSUE TITLE
Random.sample() results are biased

### ISSUE THREAD

**Issue by pbkhrv** [ckknight/random-js#7]
Thanks for making a nice library. I was looking for a seed-able PRNG and random-js fits the bill.
I was using `Random.sample(population, 1)` and noticed that it always returns the same result, namely the last item in the `population` array.
Here is test code:
```javascript
var Random = require('./random.js');
var r = new Random(Random.engines.mt19937().autoSeed());
var hits = {};
var population = ['a', 'b', 'c', 'd', 'e'];
var sampleSize = 1;
for(var i = 0; i < 100000; i++) {
  var k = r.sample(population, sampleSize).join(',');
  hits[k]++ || (hits[k] = 1); 
}
console.log(hits);
```
When I run it with `node`, it prints out the following:
    { e: 100000 }

When I use `sampleSize = 2`, the results also seem to heavily favor one of the elements of the population array:
    { 'd,b': 20013,
    'd,c': 19884,
    'd,e': 20011,
    'd,a': 20069,
    'e,d': 20023 }

This smells like an off-by-one somewhere... Or am I missing something?

Thanks.
- Peter

**Comment by ckknight** [comment]
Yep, logically, there was an off-by-one error where if you sampled by one, it would shuffle exactly 0 items rather than 1. This applied to sample and not shuffle because shuffle has no point in shuffling the very last item (since it can only shuffle with itself), whereas with sample, it needs to take the next item into account.
